# Generated by Django 5.0.7 on 2024-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='schedule_days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
