# Generated by Django 5.0.7 on 2024-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_script_schedule_days_script_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='schedule_days',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
