# Generated by Django 5.0.7 on 2024-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_alter_script_schedule_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='last_execution_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='last_execution_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='last_execution_success',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='last_execution_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
