# Generated by Django 5.0.7 on 2024-07-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_script_last_execution_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_days', models.CharField(blank=True, max_length=21, null=True)),
                ('last_execution_time', models.DateTimeField(blank=True, null=True)),
                ('last_execution_success', models.BooleanField(null=True)),
                ('last_execution_error', models.TextField(blank=True, null=True)),
                ('last_execution_duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='script',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='script',
            name='last_execution_duration',
        ),
        migrations.RemoveField(
            model_name='script',
            name='last_execution_error',
        ),
        migrations.RemoveField(
            model_name='script',
            name='last_execution_success',
        ),
        migrations.RemoveField(
            model_name='script',
            name='last_execution_time',
        ),
        migrations.RemoveField(
            model_name='script',
            name='schedule_days',
        ),
        migrations.RemoveField(
            model_name='script',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='script',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='script',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='connector.job'),
        ),
    ]
