# Generated by Django 5.0.7 on 2024-07-31 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_job_alter_script_options_remove_script_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_days',
            field=models.CharField(blank=True, default="'' ", max_length=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='script',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='connector.job'),
        ),
        migrations.AlterField(
            model_name='script',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
