# Generated by Django 5.0.7 on 2024-07-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_job_description_job_order_alter_job_schedule_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='schedule_days',
            field=models.CharField(blank=True, default='', max_length=21),
        ),
    ]
