# Generated by Django 5.0.7 on 2024-08-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_alter_job_schedule_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='column_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
