# Generated by Django 5.0.7 on 2024-08-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_script_column_names_script_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='import_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='transform_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
