# Generated by Django 5.0.7 on 2024-08-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0009_script_import_enabled_script_transform_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='run_transform',
            field=models.BooleanField(default=False),
        ),
    ]
