# Generated by Django 5.0.7 on 2024-08-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0010_script_run_transform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('related_column_name', models.CharField(blank=True, max_length=255)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='connector.script')),
            ],
            options={
                'unique_together': {('script', 'table_name', 'column_name')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('last_import', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('row_count_prev', models.IntegerField(default=0)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='connector.script')),
            ],
            options={
                'unique_together': {('script', 'table_name')},
            },
        ),
    ]
