# Generated by Django 5.0.7 on 2024-08-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_column_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='column_names',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
