# Generated by Django 5.0.7 on 2024-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_alter_script_column_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='default_column_names',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='column_names',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
