# Generated by Django 5.0.7 on 2024-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0013_table_default_column_names_alter_script_column_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
