# Generated by Django 5.0.7 on 2024-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0014_alter_table_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='column_names',
        ),
        migrations.RemoveField(
            model_name='script',
            name='run_transform',
        ),
        migrations.RemoveField(
            model_name='script',
            name='transform_script',
        ),
        migrations.AddField(
            model_name='table',
            name='override_column_names',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='run_transform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='transform_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
