# Generated by Django 5.0.7 on 2024-08-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0015_remove_script_column_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='order',
        ),
    ]
