# Generated by Django 5.0.7 on 2024-08-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_remove_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='schedule_days',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
    ]
