# Generated by Django 5.0.7 on 2024-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0017_alter_job_schedule_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('DATE', 'Date'), ('INTEGER', 'Integer'), ('STRING', 'String'), ('DECIMAL', 'Decimal'), ('BINARY', 'Binary')], default='STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='column',
            name='sample_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
