# Generated by Django 5.0.7 on 2024-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0019_alter_column_sample_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='sample_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
