# Generated by Django 5.0.7 on 2024-08-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0020_alter_column_sample_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='related_column_name',
            new_name='override_column_name',
        ),
    ]
