# Generated by Django 5.0.7 on 2024-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0021_rename_related_column_name_column_override_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='default_column_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
