# Generated by Django 5.0.7 on 2024-08-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0023_remove_column_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='data_type',
            new_name='override_data_type',
        ),
        migrations.AddField(
            model_name='column',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
