# Generated by Django 5.0.7 on 2024-08-13 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0025_column_detected_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='column',
            name='foreign_key_reference',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_unique': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_columns', to='connector.column'),
        ),
    ]
