# Generated by Django 5.0.7 on 2024-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0028_alter_script_options_rename_order_script_order_exec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='import_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
