# Generated by Django 5.0.7 on 2024-08-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_savedreportconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreportconfiguration',
            name='query_builder_rules',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
