# Generated by Django 5.0.7 on 2024-08-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_savedreportconfiguration_query_builder_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryBuilderRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_table', models.CharField(max_length=100)),
                ('to_table', models.CharField(max_length=100)),
                ('fk_column', models.CharField(max_length=100)),
                ('referenced_column', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('from_table', 'to_table', 'fk_column', 'referenced_column')},
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('is_nullable', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='reports.table')),
            ],
            options={
                'unique_together': {('table', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TableRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='reports.column')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='reports.table')),
                ('to_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='reports.column')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='reports.table')),
            ],
            options={
                'unique_together': {('from_table', 'to_table', 'from_column', 'to_column')},
            },
        ),
    ]
