# Generated by Django 5.0.7 on 2024-08-27 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_table_querybuilderrelationship_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='script',
            name='job',
        ),
        migrations.DeleteModel(
            name='QueryBuilderRelationship',
        ),
        migrations.AlterUniqueTogether(
            name='savedreportconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedreportconfiguration',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tablerelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tablerelationship',
            name='from_column',
        ),
        migrations.RemoveField(
            model_name='tablerelationship',
            name='from_table',
        ),
        migrations.RemoveField(
            model_name='tablerelationship',
            name='to_column',
        ),
        migrations.RemoveField(
            model_name='tablerelationship',
            name='to_table',
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='table',
            name='description',
        ),
        migrations.AddField(
            model_name='table',
            name='schema',
            field=models.CharField(default='public', max_length=255),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='reports.column'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='reports.table'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='reports.column'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='reports.table'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Script',
        ),
        migrations.DeleteModel(
            name='SavedReportConfiguration',
        ),
        migrations.DeleteModel(
            name='TableRelationship',
        ),
        migrations.RemoveField(
            model_name='column',
            name='is_nullable',
        ),
    ]
