# Generated by Django 5.0.7 on 2024-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='sql_report',
            field=models.BooleanField(default=False),
        ),
    ]
